name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create config files
        run: |
          cp ~/default.json src/config/default.json
          cp ~/serviceAccountKey.json src/config/serviceAccountKey.json

      - name: Set up Docker Compose
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
